version: "3.8"

services:
  boot-admin-server:
    build:
      dockerfile: ./Dockerfile
      context: ./spring-boot-admin-server
    ports:
      - "9999:8080"

  client_1:
    build:
      dockerfile: ./Dockerfile
      context: ./spring-boot-admin-client
    environment:
      SPRING_BOOT_SERVER: http://boot-admin-server:8080
    links:
      - boot-admin-server

  client_2:
    build:
      dockerfile: ./Dockerfile
      context: ./spring-boot-admin-client
    environment:
      SPRING_BOOT_SERVER: http://boot-admin-server:8080
    links:
      - boot-admin-server

  client_3:
    build:
      dockerfile: ./Dockerfile
      context: ./spring-boot-admin-client
    environment:
      SPRING_BOOT_SERVER: http://boot-admin-server:8080
    links:
      - boot-admin-server
